### ISSUE TITLE
Add check to ensure minimum host OS requirements

### ISSUE THREAD

**Issue by SuperJMN** [WOA-Project/WOA-Deployer-Lumia#10]
It should only run inside Windows 10 with 
- PowerShell 5+ 
- .NET Framework 4.6.1+

**Comment by CornyjK** [comment]
This is already here: WOA-Project/WOA-Deployer-Platform#1

**Comment by SuperJMN** [comment]
This should fix the issue: https://github.com/WOA-Project/WOA-Deployer-Lumia/blob/master/Source/Deployer.Lumia.Gui/app.manifest#L43
