### ISSUE TITLE
In the PartitionCleaner.cs there are still dependencies to volume.label. It should use partition.name

### ISSUE THREAD

**Issue by paule96** [WOA-Project/WOA-Deployer-Lumia#19]
**Describe the bug**

If you deploy the emergency-files to your lumia950xl with the WPI, it can happend that the last volume don't get the label "Data". This shouldn't be a problem for WOA because we use the GPT partition name instead of the volume name. But [one single line](https://github.com/WOA-Project/WOA-Deployer-Lumia/blob/698a55e32d84c7aa641892de193cf67b5726bc0c/Source/Deployer.Lumia/PartitionCleaner.cs#L49) in the PartitionCleaner.cs use the volume name. 
This result in an error in `Phone disk preparation failed` in the frontend that stop the deployment. If you look in the log you see the full error:
```bash
Deployer.FileSystem.PartitioningException: The label of the last partition should be 'Data' and it's ''
   bei Deployer.Lumia.PartitionCleaner.<EnsureDataIsLastPartition>d__3.MoveNext()
```

**To Reproduce**

1. Deploy your Lumia950XL with the emergency-files or with the Windows Device Recovery Tool
2. Open the disk management on check if the last partition have the label `Data`
   * if not remove that label over the propertys
3. try to deploy your WinARM via WOA and you see the error.

**Expected behavior**
No error or a message that ask me, if it should be change the volume label.

## Current workaround

go in the disk management and change the labe of the last partition to `Data`. Make sure you use the last partition. 

> If nobody grab this in the next 8h I start working on the fix by myself. But now I go to sleep. Good night internet 😎

**Comment by SuperJMN** [comment]
Fixed by https://github.com/WOA-Project/WOA-Deployer-Lumia/commit/038bc1751604c96f4510a9e00caffbea9f93cc54
