### ISSUE TITLE
Add unlocking of the bootloader to WOA Deployer

### ISSUE THREAD

**Issue by Aarklendoia** [WOA-Project/WOA-Deployer-Lumia#21]
The first step to use WOA Deployer is a bootloader unlocked. But this is very risky.

I myself killed a Lumia 950XL because my OS version was too recent to use WPInternal (smartphone blocked on the firmware update red screen, and impossible to get out except to kill the device permanently).

So if the return to an unlockable version of bootloader and the unlocking itself were managed by WOA Deployer, it would simplify the procedure!

Besides, can we recover a Lumia 950XL that is blocked at boot time (no more screen power on)?
I don't want to make my second Lumia 950XL unusable again!

**Comment by CornyjK** [comment]
We will not implement such function, about your bricked phones, ask in our Telegram group or contact <https://t.me/cornyjk>.
