### ISSUE TITLE
Force single boot enables forces dual boot

### ISSUE THREAD

**Issue by maurictg** [WOA-Project/WOA-Deployer-Lumia#24]
Please use the "Preview" tab above to view this message if you are seeing this in the new issue text box.

Please note that this is a **WoA Deployer** issue tracker, use this issue tracker only for the WoA Deployer related bugs.

Please open ticket in [WOAProject forum](https://www.woaproject.net/viewforum.php?f=17) for anything else, such as:

- Reporting bugs of other tools, drivers, etc.
- Asking for help
- Asking about project progress.

# Please remove the text above before opening an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log file**
Please put your log file here (just drag&drop it).

**Comment by CornyjK** [comment]
No description given.
