### ISSUE TITLE
Phone disk preparation failed." while formatting SYSTEM for v2.5.0

### ISSUE THREAD

**Issue by chenkaigithub** [WOA-Project/WOA-Deployer-Lumia#30]
Install windows 10 on arm for 950 failed.
Use windows 10 version:
18362.86.190423-1423.19H1_RELEASE_SVC_PROD3_CLIENTPRO_OEMRET_A64FRE_ZH-CN.ISO

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1229736/57440207-2858de00-727a-11e9-9825-045ad1e29fd6.JPG)

**Log file**
Please put your log file here (just drag&drop it).
[Log-20190509.txt](https://github.com/WOA-Project/WOA-Deployer-Lumia/files/3161127/Log-20190509.txt)

**Comment by tkiapril** [comment]
Possible duplicate issue #28, try CI build 411: https://dev.azure.com/superjmn/WOA-Deployer/_build/results?buildId=411 (Download from Artifacts->WOA Deployer)

**Comment by SuperJMN** [comment]
As @tkiapril says, please try the build he's linking. If you don't know how to do it, please, comment :)

**Comment by SuperJMN** [comment]
Reverted the changes. This should work: 2.5.1 https://github.com/WOA-Project/WOA-Deployer-Lumia/commit/055c5e1de25361db7cf6a2bd0d88d5b89d8fa379

**Comment by BaRRaKudaRain** [comment]
Maybe you should try older build?

-----Original Message-----

**Comment by chenkaigithub** [comment]
I bought an old phone to install, but it is now brick. I found about 40 partitions on the disk. So I think this issue could be raised by this partitions which is shown on 0 M.  I removed some and keep the system partitions. But the phone cannot be started anymore and the screen is always black. I am not it's a software issue or hardware issue now.

**Comment by BenNottelling** [comment]
It's not bricked just use the Microsoft device recovery tool

**Comment by chenkaigithub** [comment]
MDRT cannot detect device.

**Comment by chenkaigithub** [comment]
![image](https://user-images.githubusercontent.com/1229736/57503163-9c01f600-7321-11e9-97d4-0d887837b025.png)

**Comment by chenkaigithub** [comment]
Finally, the phone is back. But I have the same problem.

**Comment by chenkaigithub** [comment]
2.5.1 is used

**Comment by chenkaigithub** [comment]
New log is attached.
[Log-20190510.txt](https://github.com/WOA-Project/WOA-Deployer-Lumia/files/3165024/Log-20190510.txt)

**Comment by tkiapril** [comment]
Mine works with 2.5.1, so apparently it's a different issue than mine. I'm wondering if your host fails to assign a drive letter for the device, but I cannot be sure since the log file doesn't say anything about it.

**Comment by chenkaigithub** [comment]
I used another windows machine to install. It's workable. I attached the log. But now wifi/audio/Bluetooth
 is still not workable.
[Log-20190513.txt](https://github.com/WOA-Project/WOA-Deployer-Lumia/files/3171213/Log-20190513.txt)

**Comment by tkiapril** [comment]
Are you using a 950 non-XL (Talkman)? As per https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/blob/1905/README.md audio and Wi-Fi is nonfunctional for 950(MSM8992) at the moment, and will not be supported very soon as well since devs are more engaged with MSM8994.

**Comment by CornyjK** [comment]
You are using Talkman (950), which does not have those features working

**Comment by chenkaigithub** [comment]
I think format partition issue is from PowerCli. It occurs error as bellow.
![image](https://user-images.githubusercontent.com/1229736/57679287-7fd1c200-765d-11e9-8bfd-1b384b06498f.png)

![image](https://user-images.githubusercontent.com/1229736/57679243-6761a780-765d-11e9-96e3-7b4fdd8019a8.png)

![image](https://user-images.githubusercontent.com/1229736/57679220-56189b00-765d-11e9-9caf-1e64e17c0175.png)

I used another win 10 , it's workable.
![image](https://user-images.githubusercontent.com/1229736/57679340-a09a1780-765d-11e9-8994-2fa692a201f7.png)

![image](https://user-images.githubusercontent.com/1229736/57679460-f5d62900-765d-11e9-8258-6e20c7276470.png)

**Comment by chenkaigithub** [comment]
> You are using Talkman (950), which does not have those features working

Thank you. Hope Talkman could be full supported ASAP.
