### ISSUE TITLE
"Syntax error: unexpected end of input, expected comment or identifier." when trying to deploy Windows 10 for ARM build 18898

### ISSUE THREAD

**Issue by tamto33** [WOA-Project/WOA-Deployer-Lumia#33]
**Describe the bug**
After hitting the Deploy button, WoA Deployer reports: "Syntax error: unexpected end of input, expected comment or identifier."

**To Reproduce**
Deploy Windows 10 for ARM build 18898 using latest WoA Deployer

**Expected behavior**
Deploying the Windows normally

**Screenshots**
![image](https://user-images.githubusercontent.com/50691862/57829860-889bd280-77da-11e9-9a39-e46b9a39befd.png)

**Log file**
[Log-20190516.txt](https://github.com/WOA-Project/WOA-Deployer-Lumia/files/3185587/Log-20190516.txt)

**Comment by SuperJMN** [comment]
OK, check this folder inside WOA Deployer: 
"Scripts\Talkman" 
Then, open the file SingleSim.txt. Is it empty? what does it contain?

**Comment by SuperJMN** [comment]
Fixed with https://github.com/WOA-Project/WOA-Deployer-Lumia/commit/3e85e12276129797d57abdfa960436b4f1faf7b0
