### ISSUE TITLE
[Error] Phone disk preparation failed. The partition size cannot be negative: -9.77 GB

### ISSUE THREAD

**Issue by cikeZ00** [WOA-Project/WOA-Deployer-Lumia#37]
**Describe the bug**
WOA tries to resize the data partition to "-9.77 GB"
which ofc leads to the "Phone disk preparation failed" error

**Expected behavior**
WOA resizes the partition normally and the installation proceeds

**Log file**
[Log-20190528.txt](https://github.com/WOA-Project/WOA-Deployer-Lumia/files/3229890/Log-20190528.txt)

Edit: This might be the reason why:
Possible it doesnt notice the already existing windows arm partition 
![image](https://user-images.githubusercontent.com/17727672/58516410-282c6e00-81a8-11e9-8305-fbbfda3e7730.png)

**Comment by EbrahimBGA** [comment]
The same issue,
![part](https://user-images.githubusercontent.com/40761377/58742380-d40cce00-83e1-11e9-84ac-5b4426fbff6e.PNG)

**Comment by SuperJMN** [comment]
Check with DISKPART the partition layout you have. Disk Management tool doesn't show some types os partitions that may be "hidden" and could prevent you from the deploying.

**Comment by cikeZ00** [comment]
Update on the whole thing.

So i managed to get it to work by resetting all the partitions back to how it was on stock.
Easiest way to fix this issue is to flash the stock FFU image and then deploy.
So im guessing its because of the old deployments. or possibly the drive letters changing, because i did this on a fresh install of windows.
