### ISSUE TITLE
Dual Boot not working on my 950XL

### ISSUE THREAD

**Issue by falkor2k15** [WOA-Project/WOA-Deployer-Lumia#50]
"Error
Value cannot be null.
Parameter name: paths"

This happened on new PCs that were not used to originally deploy WOA - but all the drivers and software was put back and now WOA Deployer cannot be used to dual boot.

How to get WOA Deployer working again - or how to get to download mode so I can recover the phone? All I can get to is Mass Storage via the developer menu. I don't have my old PC anymore.

**Comment by falkor2k15** [comment]
No worries - I think I've solved it by redeploying a fresh WOA.

**Comment by gus33000** [comment]
Person said the issue was solved, closing as a result
