### ISSUE TITLE
Remove unattend file during deployment

### ISSUE THREAD

**Issue by falkor2k15** [WOA-Project/WOA-Deployer-Lumia#52]
So that we can use our own unattend(answer) file for OOBE during initial deployment of WOA.

**Comment by gus33000** [comment]
The unattended file is required for most drivers to get installed properly. You can however modify it, but keep the script section. If you only need to run scripts, then you can update the scripts themselves or add some using the mechanism supported. This issue isn't related to woa deployer, closing.
