### ISSUE TITLE
Change of WOA Deployer, Installation of new default Driverpackage only

### ISSUE THREAD

**Issue by pachnes** [WOA-Project/WOA-Deployer-Lumia#54]
Hi!

Could you change WOA deployer with an extra Menu, which only does download and install (inject) the newest release of the driver package?

Now with every new release of a new driver package, we have to reinstall all software on the phone and than have to start from scratch, to configure Windows 10 :)

Thanks!
Thomas

**Comment by gus33000** [comment]
The driver package itself doesn't support any way of upgrading. Using dism again will result in no update done due to various issues and how some drivers get installed. This can't be fixed
