### ISSUE TITLE
Mobile phone network: "The account is not active"  [question] [tech support required]

### ISSUE THREAD

**Issue by tymcarlos** [WOA-Project/WOA-Deployer-Lumia#55]
I have used Woa Deployer version 2.6 to install Windows 10 pro ARM on a Lumia 950 XL with all the instructions and checking that all Cityman drivers have been loaded, however the CELLULAR still does not work, although in STATUS it is indicated that It works for both data and calls.
When the cell phone is opened it indicates "phone deactivated" and in networks Mobile phone network: "The account is not active"
I have installed it several times and it has been restarted in each of them also multiple times without obtaining success so far, of course it has an active SIM.
Performed the same steps with the Lumia 950 I get the same result, both the mobile phone network and the phone (Cellular) say account is not active or deactivated. There is still no phone connection when it starts in Windows 10 Arm.
Since the SIM card does detect it, it is logical to think that it is due to the telephone company, the one that appears in the images of imgur.com are from SFR (France) and my company is movistar (Spain).

**Comment by gus33000** [comment]
Not related to woa deployer, closing. (Issue also got fixed on the driver front of things ever since)

**Comment by tymcarlos** [comment]
Rotten lie

Enviado desde mi dispositivo con Windows 10

De: Gustave Monce<mailto:notifications@github.com>
Enviado: sábado, 28 de marzo de 2020 16:17
Para: WOA-Project/WOA-Deployer-Lumia<mailto:WOA-Deployer-Lumia@noreply.github.com>
CC: TymCarlos<mailto:carlostortajada@live.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [WOA-Project/WOA-Deployer-Lumia] Mobile phone network: "The account is not active" [question] [tech support required] (#55)


Not related to woa deployer, closing. (Issue also got fixed on the driver front of things ever since)

**Comment by SuperJMN** [comment]
@tymcarlos, it's not a lie. It has nothing to do with WOA Deployer. Sorry.

**Comment by CornyjK** [comment]
😂😂😂
