### ISSUE TITLE
32 bit arm support (possible)

### ISSUE THREAD

**Issue by jor1196** [WOA-Project/WOA-Deployer-Lumia#57]
Hello good, I have seen that youtuber managed to run windows 10 on a lumia 640xl (with 8gb), also did it with a windows 8 rt

Would you consider supporting other devices that had windows mobile?

I leave you my proof that it was possible
https://www.youtube.com/watch?v=T5WhhGP6RFI

**Comment by lamdemon** [comment]
The answer is: NO!!!
