### ISSUE TITLE
Add lumia 640 support

### ISSUE THREAD

**Issue by fisforfaheem** [WOA-Project/WOA-Deployer-Lumia#69]
Millions still use it and it will run the windows 10 please do it

**Comment by DremOSDeveloperTeam** [comment]
Not only is this probably impossible, but it's even more underpowered than the Lumia 950 so it would be unbearable if it ever worked at all.

**Comment by fisforfaheem** [comment]
Atleast make an app to revive these older devices by throwing in some performanc eimproving hacks please

**Comment by DremOSDeveloperTeam** [comment]
One does not simply "make an app" that can "throw in some performance improving hacks". The closest thing to what you want is a [custom ROM](https://forum.xda-developers.com/windows-10-mobile/th2-restone-windows-10-custom-roms-t3440144/amp/) but I have no clue if there is a custom ROM for your phone or if they would help performance. This, however, is out of the scope of this project.

**Comment by fisforfaheem** [comment]
Oh k! bro Please Please Do something great! and show us work hard and release!
