### ISSUE TITLE
xiaomi4 support windows mobile system, could this project support this device?

### ISSUE THREAD

**Issue by Fankbai** [WOA-Project/WOA-Deployer-Lumia#72]
xiaomi 4 phone was support by windows mobile os. and I noticed the BDS menu shows system can be setting as boot USB first. so is this possible to install windows 10 arm os into my xiaomi4?

**Comment by SuperJMN** [comment]
No, sorry. In order to support a device we need: 
Also, the CPU should be supported by WOA, like some Qualcomm Snapdragon processors.
UEFI + drivers.
