### ISSUE TITLE
Is it possible to update Windows as on PC? (via Microsoft Update)

### ISSUE THREAD

**Issue by chiaravalle** [WOA-Project/WOA-Deployer-Lumia#73]
Hello everyone.
As in subject, I wonder if is it possible to update WoA using Microsoft Update, just in case a newer version comes up.
Is it possible, or am I required to download and flash every time?

Thanks in advance for any help.

**Comment by SuperJMN** [comment]
It's possible as long as you disable Dual Boot before the updating (the dual boot option that enables Windows 10 Phone + WOA).

**Comment by chiaravalle** [comment]
Thanks a lot

**Comment by chiaravalle** [comment]
Dumb question: when I installed, I didn't made it dual boot.
Am I required to tweak something anyhow?

Thanks in advance.

**Comment by SuperJMN** [comment]
No, if you don't touch anything, it should update just right.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by chiaravalle** [comment]
Ok, thanks a lot more

**Comment by chiaravalle** [comment]
One last question: does updating break driver compatibility? I'm running build 18363, if I update, will drivers quit working?

**Comment by chiaravalle** [comment]
Nevermind, I just registered in the forums, and I'll look there for answers.
Please, discard my messages.
