### ISSUE TITLE
Driver update - reflash?

### ISSUE THREAD

**Issue by chiaravalle** [WOA-Project/WOA-Deployer-Lumia#74]
Hello everyone.
Is it possible to update WoA drivers without flashing the image again?
If so, how?

Thanks in advance for any help.

**Comment by chiaravalle** [comment]
P.S.: I need to manually install GPU and Mobile Phone Drivers, where can I find them?
And how can I install them?
I'm using Latest Public Release Build

**Comment by SuperJMN** [comment]
I'm sorry, we're out of luck. Because the way that drivers are installed and their interdependencies, it's not possible to reinstall/update the drivers. You need to flash/redeploy.

**Comment by chiaravalle** [comment]
Ok, which image should I flash to get them?

**Comment by chiaravalle** [comment]
I guess the drivers are the same, even on most recent builds. Aren't they? If so, I won't need to reflash, correct?

**Comment by chiaravalle** [comment]
Please, tell me

**Comment by chiaravalle** [comment]
Nevermind, I just registered in the forums, and I'll look there for answers.
Please, discard my messages.
