### ISSUE TITLE
WOA Deployer crash at 85%~100% of the WOA backup.

### ISSUE THREAD

**Issue by GlitchedCod** [WOA-Project/WOA-Deployer-Lumia#77]
Hello there !
I'm a new WOA user (yay a new WOA user !) because i just recently found a 950 Nokia Lumia for approximatively 25$ and i just wanted to give it a try. fter i have followed every steps from unlocking the bootloader to installing succefully Windows 10 ARM in dualboot with Winows 10 Phone but now i want to reset all to reinstall Windows 10 Phone to get all the latests updates and after restoring a WOA backup but when i go to the Advanced Mode in WOA Deployer and choose from the "WOA Partition manager" the "backup" one i get a crash error (a window for crash with red mark with the memory location) at the end of the backup and i finish with only a 7 or 8 Go backup but i don't know if he's usable and i don't want tot try restore this one to see if he's working or not. I have installed the latest Windows 10 ARM and the latest WOA Deployer, if someone can help me or say how to backup with another way only the WOA partition that would be great ! 💯 
And btw if you need some people to try some stuff to test on their device i'm in !

**Comment by SuperJMN** [comment]
Backup feature has been disregarded. Please, use regular deployments instead.
