### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by TyTytheFurKit** [WOA-Project/WOA-Deployer-Lumia#85]
I've downgraded to Windows 7 recently, and I decided to see if there would be any different results when connecting the Lumia 950 i have to my computer while Windows 10 on arm was booted, there was a MAJOR difference, I can access the SD Card I have in there directly and the MainOS Partition from the Windows 10 Mobile OS, and it will live update both when I make changes from the phone or the computer I use, and it uses a Windows 11 on Lumia icon for when it's booted into that mode.
![image](https://user-images.githubusercontent.com/69062095/132929999-c548fd33-0efd-46f2-9a88-990819f29b74.png)
![image](https://user-images.githubusercontent.com/69062095/132930018-2ea13be5-556b-4380-b416-d9e995136865.png)
Is this expected behavior? I'm just really amazed by this and I want to be sure that by it doing this it isn't damaging the phone in anyway.

**Comment by TyTytheFurKit** [comment]
![image](https://user-images.githubusercontent.com/69062095/132930075-a1e34fa0-4334-4852-877d-107315e8de10.png)
It even has the version number inside the Device Properties Dialog

**Comment by SuperJMN** [comment]
Yes, that's normal. You should thank @gus33000 for that :)
