### ISSUE TITLE
JUNK JUST PURE JUNK I'M SO MAD AN ENTIRE DAY WASTED I WAITED FOR SO MANY HOURS USING UUPDUMP TWICE AND THEN JUST USING AN OFFICIAL .iso FROM MICROSOFT'S MEDIA CREATION TOOL AND THE EXACT SAME THING I SELECT THE install.wim FROM UUPDUMP OR THE install.esd FROM THE OFFICIAL .iso AND IT IMMEDIATELY FLAT OUT REFUSES EVERY TIME WITHOUT FAIL AND THROWS A BS ERROR "Invalid WIM file"  "Could not read the metadata from the WIM file. Please, check it's a valid .WIM file" AND THE ONLY OPTION IS "OK" IT DOESN'T EVEN TRY

### ISSUE THREAD

**Issue by 44cK3r** [WOA-Project/WOA-Deployer-Lumia#90]
Please use the "Preview" tab above to view this message if you are seeing this in the new issue text box.

Please note that this is a **WoA Deployer** issue tracker, use this issue tracker only for the WoA Deployer related bugs.

Please open ticket in other repositories for anything else, such as:

- Reporting bugs of other tools, drivers, etc.
- Asking for help
- Asking about project progress.

# Please remove the text above before opening an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log file**
Please put your log file here (just drag&drop it).

**Comment by Xuyiyang23333** [comment]
Calm down and try this.
https://www.reddit.com/r/windowsphone/comments/15s1mvc/woa_deployer_image_compatibility/
```
DISM /Export-Image /SourceImageFile:[downloaded install.wim] /SourceIndex:1 /DestinationImageFile:[new install.wim destination] /CheckIntegrity
```

**Comment by 44cK3r** [comment]
> Calm down and try this.
> https://www.reddit.com/r/windowsphone/comments/15s1mvc/woa_deployer_image_compatibility/
> ```
> DISM /Export-Image /SourceImageFile:[downloaded install.wim] /SourceIndex:1 /DestinationImageFile:[new install.wim destination] /CheckIntegrity
> ```

Ok thank you
